### ISSUE TITLE
adding functions for explicit conversions

### ISSUE THREAD

**Issue by zhangchiqing** [soenkehahn/string-conversions#16]
Does it make sense to add functions that have explicit types, with no typeclass?

```haskell
stringToByteString :: String -> B.ByteString
stringToByteString = cs

stringToLazyByteString :: String -> BL.ByteString
stringToLazyByteString = cs

stringToText :: String -> T.Text
stringToText = cs

stringToLazyText :: String -> TL.Text
stringToLazyText = cs

textToString :: T.Text -> String
textToString = cs

...
```

**Comment by soenkehahn** [comment]
Have you seen this module: https://github.com/soenkehahn/string-conversions/blob/master/src/Data/String/Conversions/Monomorphic.hs ? It's not the same you're asking for, but the types are less generic than in `cs`.

> Does it make sense to add functions that have explicit types, with no typeclass?

Not sure. Do you have a usecase where you would prefer to use the functions you propose over `cs` or the functions from `Data.String.Conversions.Monomorphic`?

**Comment by zhangchiqing** [comment]
Yes. That works. Thanks
